# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: true
disqus_shortname: lutece-blog

# google analytics
googleTrackId:

# baidu analytics
baiduTrackId:

menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about

read_more_btn: true
